### ISSUE TITLE
doesnt build on Mac OSX M2

### ISSUE THREAD

**Issue by opensubtitles** [vankasteelj/opensubtitles-uploader#114]
I would like to test and fix why it is giving 503, but without building it, I can not. If it is possible to make CURL example what is failing it would be perfect.

```
❯ gulp build
(node:93420) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[08:45:50] Using gulpfile ~/opensubtitles-uploader/gulpfile.js
[08:45:50] Starting 'build'...
[08:45:50] Starting 'npm:modclean'...
ModClean: 3752 files/folders removed
[08:45:51] Finished 'npm:modclean' after 449 ms
[08:45:51] Starting 'nwjs'...
[08:45:51] 'nwjs' errored after 1.69 ms
[08:45:51] Error: No platform to build!
    at new NwBuilder (/Users/os/opensubtitles-uploader/node_modules/nw-builder/lib/index.js:100:15)
    at /Users/os/opensubtitles-uploader/gulpfile.js:173:16
    at taskWrapper (/Users/os/opensubtitles-uploader/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (node:domain:432:15)
    at runBound (node:domain:443:12)
    at asyncRunner (/Users/os/opensubtitles-uploader/node_modules/async-done/index.js:55:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
[08:45:51] 'build' errored after 452 ms
```

search brings to
https://npmdoc.github.io/node-npmdoc-nw-builder/build/apidoc.html

```
    if (this.options.platforms.length === 0)
        throw new Error('No platform to build!');
```

I am not node developer, so I dont even know what to change.

**Comment by vankasteelj** [comment]
I cannot provide support for Apple, see https://github.com/vankasteelj/opensubtitles-uploader#common-issues

**Comment by andrericardo** [comment]
With current master was able to build on M3 by just using the default osx64 platform since most ARM just works as Intel.

```sh
npm install -g gulp-cli
npm install

gulp build --platforms osx64
```

Longer log
```sh
gulp build --platforms osx64

   ╭─────────────────────────────────────────────────────────────────╮
   │                                                                 │
   │   nw-builder update available (3.5.7 → 4.13.7)                  │
   │   To update, run one of the following commands:                 │
   │   - npm i -g nw-builder (if nw-builder is installed globally)   │
   │   - npm i -D nw-builder (if nw-builder is installed locally)    │
   │                                                                 │
   ╰─────────────────────────────────────────────────────────────────╯

[20:31:44] Using gulpfile ~/code/opensubtitles-uploader/gulpfile.js
[20:31:44] Starting 'build'...
[20:31:44] Starting 'npm:modclean'...
ModClean: 3768 files/folders removed
[20:31:44] Finished 'npm:modclean' after 479 ms
[20:31:44] Starting 'nwjs'...
Using v0.76.0 (sdk)
Create cache folder in /Users/andre/code/opensubtitles-uploader/cache/0.76.0-sdk
Downloading: https://dl.nwjs.io/v0.76.0/nwjs-sdk-v0.76.0-osx-x64.zip
  downloading [====================] 100% 0.0s

Create release folder in /Users/andre/code/opensubtitles-uploader/build/opensubtitles-uploader/osx64
[20:31:56] Finished 'nwjs' after 12 s
[20:31:56] Starting 'clean:mediainfo'...
clean:mediainfo osx64
[20:31:56] Finished 'clean:mediainfo' after 6.63 ms
[20:31:56] Starting 'clean:nwjs'...
[20:31:56] Finished 'clean:nwjs' after 4.56 ms
[20:31:56] Starting 'build:prune'...

up to date, audited 818 packages in 5s

64 packages are looking for funding
  run `npm fund` for details

30 vulnerabilities (14 moderate, 13 high, 3 critical)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

[20:32:02] Finished 'build:prune' after 5.5 s
[20:32:02] Finished 'build' after 18 s
```

Finally run

```sh
gulp run --platforms osx64
```

<img width="1136" alt="image" src="https://github.com/user-attachments/assets/56cea4f1-0794-42d6-b0bc-e3329110b0ec" />

Success verifying an hash :)

<img width="517" alt="image" src="https://github.com/user-attachments/assets/65d1d370-9bea-45b6-b783-bc74cac24840" />

**Comment by varenc** [comment]
Just to chime in... would really love more official macOS support.

I had errors trying to do `gulp build --platforms osx64` and `gulp run --platforms osx64`, but I was able to at least get this running locally by just running `nw .`

**Comment by opensubtitles** [comment]
I am developing REACT app to replace upload system on opensubtitles.org and maybe I will release it publicly.

**Comment by varenc** [comment]
> I am developing REACT app to replace upload system on opensubtitles.org and maybe I will release it publicly.

that would be great!  (Hopefully can still calculate the source media's file hash without uploading it. I think that's possible with modern browsers)

**Comment by opensubtitles** [comment]
Sure, the demo is available on uploader.opensubtitles.org (github too) - you can try. Still in development.
